#ifndef _WTRERRNO_H_
#define _WTRERRNO_H_

#define E_WTRIE_ORPHAN      340
#define E_WTRIE_DUPCHILD    341
#define E_WTRIE_INITFAILED  342
#define E_WTRIE_SPAWNFAILED 343
#define E_WTRIE_NOSUCHNODE  3404
#define E_WTRIE_CORRUPT     345
#define E_WTRIE_EMPTYWORD   346
#define E_WTRIE_NULLPOINTER 347
#define E_WTRIE_NOSUCHWORD  348

#define W_WTRIE_METANOTSET  360

#define I_WTRIE_NOSUCHWORD  388

#endif
